import express from 'express';
import '../utils/mongo.js';
import userRoute from "../router/user.routes.js";
import postRoute from "../router/post.routes.js";
import commentRoute from "../router/comment.routes.js";
const PORT = 5000;
const app = express();
app.use(express.json());
app.use(userRoute);
app.use(postRoute);
app.use(commentRoute);
app.listen(PORT), console.log('server ishladi....');